require('settings')
require('mappings')
require('colorschemes-config.nightfox')
require('packer-config')
-- require('treesitter-config')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('luasnip-config')
require("autopairs-config")
require("nvim-comment")
require("lualine-config")
